[package]
name = "java-AST"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    "macro_attribute",
]

[dependencies]
nom = { version = "8.0.0-beta.1" }
macro_attribute = { path = "macro_attribute" }
